In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV,cross_val_score
from sklearn.metrics import mean_squared_error,r2_score

from sklearn import model_selection
from sklearn.neighbors import KNeighborsRegressor

from warnings import filterwarnings
filterwarnings('ignore')

ModuleNotFoundError: No module named 'seaborn'

# Train-Test

In [9]:
df = pd.read_csv('tips.csv')

In [10]:
df.head()

fiyat  bahşiş  cinsiyet  sigara  gün  zaman  kişiler
0  16.99    1.01         1       2    4      2        2
1  10.34    1.66         2       2    4      2        3
2  21.01    3.50         2       2    4      2        3
3  23.68    3.31         2       2    4      2        2
4  24.59    3.61         1       2    4      2        4

In [11]:
x = df.drop(["fiyat"] , axis=1)
y = df["fiyat"]

In [12]:
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [13]:
x_train.shape

(195, 6)

In [14]:
x_test.shape

(49, 6)

In [15]:
y_train.shape

(195,)

In [16]:
y_test.shape

(49,)

# Model Oluşturma

In [17]:
knn_model = KNeighborsRegressor()

In [18]:
knn_model

KNeighborsRegressor()

In [19]:
model = knn_model.fit(x_train,y_train)

In [20]:
model

KNeighborsRegressor()

In [21]:
new_data = [[2],[1],[1],[1],[1],[2]]

In [27]:
new_data = pd.DataFrame(new_data).T

In [28]:
new_data

0  1  2  3  4  5
0  2  1  1  1  1  2

In [29]:
model.predict(new_data)

array([13.694])

In [30]:
y_pred = model.predict(x_test)

In [34]:
y_pred[0:10]

array([14.982, 15.632, 19.088, 30.012, 13.694, 19.398, 15.738, 14.512,
       18.522, 22.062])

# Test Hatası Öğrenme

In [35]:
np.sqrt(mean_squared_error(y_test,y_pred))

6.698439154164261

# Eğitim Hatası

In [36]:
np.sqrt(mean_squared_error(y_train,model.predict(x_train)))

5.122797228678278

In [40]:
for k in range(30) :
    k=k+1
    k_model = KNeighborsRegressor(n_neighbors = k).fit(x_train,y_train)
    y_pred = k_model.predict(x_train)
    hata=np.sqrt(mean_squared_error(y_train,y_pred))
    
    print("k değeri = ",k, " hata değeri = ",hata)

k değeri =  1  hata değeri =  1.4968462572852022
k değeri =  2  hata değeri =  4.167074959482817
k değeri =  3  hata değeri =  4.6896942598331774
k değeri =  4  hata değeri =  5.079752823711012
k değeri =  5  hata değeri =  5.122797228678278
k değeri =  6  hata değeri =  5.2772201468796505
k değeri =  7  hata değeri =  5.445193549279551
k değeri =  8  hata değeri =  5.470083982356986
k değeri =  9  hata değeri =  5.6697702986099605
k değeri =  10  hata değeri =  5.766707951682658
k değeri =  11  hata değeri =  5.818068288883619
k değeri =  12  hata değeri =  5.813599419964534
k değeri =  13  hata değeri =  5.858655167374318
k değeri =  14  hata değeri =  5.9173129703536596
k değeri =  15  hata değeri =  5.999474977978991
k değeri =  16  hata değeri =  6.016636113160668
k değeri =  17  hata değeri =  6.045158835209828
k değeri =  18  hata değeri =  6.024856869466902
k değeri =  19  hata değeri =  6.026635165060382
k değeri =  20  hata değeri =  6.066968984296051
k değeri =  21  hata değ

# en ideal k değeri bulma

In [41]:
knn_values = {"n_neighbors": np.arange(1,30,1)}

In [42]:
knn = KNeighborsRegressor()

In [43]:
knn_cv_model = GridSearchCV(knn,knn_values,cv=10)

In [44]:
knn_cv_model.fit(x_train,y_train)

GridSearchCV(cv=10, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])})

In [45]:
knn_cv_model.best_params_

{'n_neighbors': 6}

# ideal k değeri ile model oluşturma

In [50]:
model = KNeighborsRegressor(n_neighbors = 6)

In [51]:
model_knn = model.fit(x_train,y_train)

In [52]:
model_knn

KNeighborsRegressor(n_neighbors=6)

In [57]:
model_knn.predict(new_data)

array([13.14666667])

In [61]:
y_pred = model.predict(x_test)

In [62]:
y_test[0:10]

24     19.82
6       8.77
153    24.55
211    25.89
198    13.00
176    17.89
192    28.44
124    12.48
9      14.78
101    15.38
Name: fiyat, dtype: float64

In [67]:
t_d = pd.DataFrame({"y_test": y_test,
              "tahmin edilen değerler": y_pred})
t_d

y_test  tahmin edilen değerler
24    19.82               15.471667
6      8.77               14.683333
153   24.55               20.386667
211   25.89               29.225000
198   13.00               13.146667
176   17.89               18.001667
192   28.44               15.848333
124   12.48               14.136667
9     14.78               17.545000
101   15.38               22.176667
45    18.29               16.641667
233   10.77               14.366667
117   10.65               10.958333
177   14.48               18.001667
82    10.07               12.328333
146   18.64               10.958333
200   18.71               21.956667
15    21.58               18.315000
66    16.45               18.651667
142   41.19               28.951667
33    20.69               24.540000
19    20.65               19.618333
109   14.31               20.916667
30     9.55               14.366667
186   20.90               23.236667
120   11.69               14.003333
10    10.27               12.836667
73    25.28               16.631667
159   16.49               20.386667
156   48.17               27.978333
112   38.07               22.698333
218    7.74               15.773333
25    17.81               19.368333
60    20.29               19.896667
18    16.97               21.881667
119   24.08               20.545000
97    12.03               16.150000
197   43.11               26.501667
139   13.16               15.283333
241   22.67               15.118333
75    10.51               14.366667
127   14.52               12.830000
113   23.95               15.921667
16    10.33               15.961667
196   10.34               13.580000
67     3.07               12.718333
168   10.59               15.350000
38    18.69               19.486667
195    7.56               12.311667

In [68]:
t_d["fark"] = t_d["y_test"] - t_d["tahmin edilen değerler"]

In [69]:
t_d

y_test  tahmin edilen değerler       fark
24    19.82               15.471667   4.348333
6      8.77               14.683333  -5.913333
153   24.55               20.386667   4.163333
211   25.89               29.225000  -3.335000
198   13.00               13.146667  -0.146667
176   17.89               18.001667  -0.111667
192   28.44               15.848333  12.591667
124   12.48               14.136667  -1.656667
9     14.78               17.545000  -2.765000
101   15.38               22.176667  -6.796667
45    18.29               16.641667   1.648333
233   10.77               14.366667  -3.596667
117   10.65               10.958333  -0.308333
177   14.48               18.001667  -3.521667
82    10.07               12.328333  -2.258333
146   18.64               10.958333   7.681667
200   18.71               21.956667  -3.246667
15    21.58               18.315000   3.265000
66    16.45               18.651667  -2.201667
142   41.19               28.951667  12.238333
33    20.69               24.540000  -3.850000
19    20.65               19.618333   1.031667
109   14.31               20.916667  -6.606667
30     9.55               14.366667  -4.816667
186   20.90               23.236667  -2.336667
120   11.69               14.003333  -2.313333
10    10.27               12.836667  -2.566667
73    25.28               16.631667   8.648333
159   16.49               20.386667  -3.896667
156   48.17               27.978333  20.191667
112   38.07               22.698333  15.371667
218    7.74               15.773333  -8.033333
25    17.81               19.368333  -1.558333
60    20.29               19.896667   0.393333
18    16.97               21.881667  -4.911667
119   24.08               20.545000   3.535000
97    12.03               16.150000  -4.120000
197   43.11               26.501667  16.608333
139   13.16               15.283333  -2.123333
241   22.67               15.118333   7.551667
75    10.51               14.366667  -3.856667
127   14.52               12.830000   1.690000
113   23.95               15.921667   8.028333
16    10.33               15.961667  -5.631667
196   10.34               13.580000  -3.240000
67     3.07               12.718333  -9.648333
168   10.59               15.350000  -4.760000
38    18.69               19.486667  -0.796667
195    7.56               12.311667  -4.751667

In [72]:
np.sqrt(mean_squared_error(y_train,model_knn.predict(x_train)))

5.2772201468796505

In [76]:
np.sqrt(-1 * cross_val_score(model_knn,x_train,y_train,cv=10,scoring='neg_mean_squared_error')).mean()

6.255230992802162