In [2]:
import numpy as np

# Array Operations

In [8]:
x = np.array([1,2,3]) # two arrays must have the same number of elements.
y = np.array([3,5,7])
a = [1,2,3]

x * y

array([ 3, 10, 21])

In [4]:
x + y

array([ 4,  7, 10])

In [9]:
3 * a

[1, 2, 3, 1, 2, 3, 1, 2, 3]

# Array Attribute

In [4]:
x = np.zeros((2,3))

x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
y = np.zeros((2,5,4))

y

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [6]:
x.shape

(2, 3)

In [7]:
y.shape

(2, 5, 4)

In [8]:
x.ndim

2

In [9]:
y.ndim

3

In [10]:
x.size

6

In [11]:
y.size

40

In [12]:
x.dtype 

dtype('float64')

In [13]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
a.ndim

1

In [15]:
a.size

10

In [23]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [24]:
a.reshape(2,5).ndim

2

In [25]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [28]:
a = np.arange(1,11)

In [29]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [30]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [31]:
x=a[np.newaxis,:]
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

# Concatenation

In [32]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])


In [33]:
np.concatenate([a,b])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
l = [10,11]

In [36]:
np.concatenate([a,b,l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [38]:
l = [10,11,"12"]
np.concatenate([a,b,l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '12'],
      dtype='<U11')

# Size Mismatch

In [39]:
a = np.array([1,2,3,4])
x = np.array([[1,2,3],[4,5,6]])

In [40]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
x.size

6

In [42]:
x.shape

(2, 3)

In [43]:
a.shape

(4,)

In [44]:
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [46]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate([x,x],axis=1) # if axis = 0, it would have merged in the y coordinate (default) but when axis = 1, it merged in the x coordinate.

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Stack

In [48]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [49]:
a

array([1, 2, 3, 4])

In [50]:
b

array([5, 6, 7, 8])

In [51]:
a.shape

(4,)

In [52]:
b.shape

(4,)

In [53]:
np.stack([a,b]) # Create a new dimension and combine it

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
np.stack([a,b],axis=1) 

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Splitting

In [66]:
l = [0,10,20,30,40,50,60,70]

In [67]:
l

[0, 10, 20, 30, 40, 50, 60, 70]

In [68]:
# [0,1], [2,3,4,5], [6,7] 
np.split(l,[2,6])

[array([ 0, 10]), array([20, 30, 40, 50]), array([60, 70])]

In [69]:
np.split(l,[3,5])

[array([ 0, 10, 20]), array([30, 40]), array([50, 60, 70])]

In [78]:
a = np.array([0,10,20,30,40,50,60,70])

In [79]:
a = np.split(a,[1,7])

In [84]:
a,b = (1,10)
print(a)
print(b)

1
10


In [85]:
x,y,z = np.split(l,[2,6])

In [87]:
print(x)
print(y)
print(z)

[ 0 10]
[20 30 40 50]
[60 70]


# VSplit

In [88]:
a = np.arange(20).reshape(2,10)

In [89]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [90]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [91]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# HSplit

In [92]:
a = np.arange(20).reshape(2,10)

In [93]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [96]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [97]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [98]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [99]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [100]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [101]:
x,y = np.hsplit(a,[2])

In [102]:
print(x)
print(y)

[[ 0  1]
 [10 11]]
[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [103]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [104]:
x,y,z = np.hsplit(a,[2,4])

In [105]:
print(x)

[[ 0  1]
 [10 11]]


In [106]:
print(y)

[[ 2  3]
 [12 13]]


In [107]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


In [108]:
a = np.arange(20).reshape(5,4)

In [109]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [110]:
np.vsplit(a,[2,3])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [111]:
np.vsplit(a,[2,3])[2]

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

# Sorting

In [112]:
a = np.array([20,32,5,30,10])

In [113]:
a

array([20, 32,  5, 30, 10])

In [114]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [115]:
a

array([20, 32,  5, 30, 10])

In [116]:
a.sort()

In [117]:
a

array([ 5, 10, 20, 30, 32])

In [127]:
a = np.array([5 ,4 ,6, 7,2])
a

array([5, 4, 6, 7, 2])

In [122]:
idxs = np.argsort(a)
a.sort()

In [126]:
print(idxs)
print(a)

[4 1 0 2 3]
[2 4 5 6 7]


# Multidimensional Array

In [128]:
a = np.arange(1,21).reshape(4,5)

In [129]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [130]:
a[0]

array([1, 2, 3, 4, 5])

In [131]:
a[0][1]

2

In [132]:
a[0,1]

2

In [133]:
a[0].ndim

1

In [134]:
a[1,1] = 10

In [135]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [136]:
a[1,1] = 10.2

In [137]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Slice Indexing

In [138]:
a = np.arange(1,21).reshape(4,5)

In [139]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [140]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [141]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [143]:
a[2:]

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [144]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [145]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [158]:
a = np.arange(1,101).reshape(10,10)

In [159]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [160]:
a[1::2]

array([[ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [161]:
a[:,3]

array([ 4, 14, 24, 34, 44, 54, 64, 74, 84, 94])

In [162]:
a[::2,3]    

array([ 4, 24, 44, 64, 84])

In [163]:
a[0,2:4]

array([3, 4])

In [164]:
a[0:2,0:3]

array([[ 1,  2,  3],
       [11, 12, 13]])

In [165]:
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [166]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [167]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [168]:
a = np.arange(1,13).reshape(3,4)

In [169]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [170]:
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

# Fancy Indexing

In [171]:
x = np.arange(1,15)

In [172]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [177]:
idxs = [4,5,7,1]

In [178]:
x[idxs]

array([5, 6, 8, 2])

In [185]:
a = np.arange(12).reshape(3,4)

In [186]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
a[0:2,1]

array([1, 5])

In [188]:
a[0:2,1].shape

(2,)

In [189]:
a[0:2,1:3]

array([[1, 2],
       [5, 6]])

In [190]:
a[0:2,1:3].shape

(2, 2)

In [191]:
a[0,[1,3]]

array([1, 3])

In [192]:
a[0,[1,3]].ndim

1

In [193]:
a = np.arange(20).reshape(4,5)

In [194]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [195]:
idx1 = [1,3,2]
idx2 = [3,0,2]

In [196]:
a[idx1,idx2]

array([ 8, 15, 12])

In [197]:
a[idx1][idx2]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [198]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [199]:
x[[1,2,3]] = 20

In [200]:
x

array([ 1, 20, 20, 20,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [202]:
x = np.arange(9)

In [203]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [204]:
x[[1,2,5]] = [100,200,300]

In [205]:
x

array([  0, 100, 200,   3,   4, 300,   6,   7,   8])

# Subarray

In [210]:
a = np.arange(1,21).reshape(4,5)

In [211]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [212]:
b = a[:2,:3]

In [213]:
b

array([[1, 2, 3],
       [6, 7, 8]])

In [214]:
b.ndim

2

In [215]:
b[0,0] = 100

In [216]:
b

array([[100,   2,   3],
       [  6,   7,   8]])

In [217]:
a

array([[100,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15],
       [ 16,  17,  18,  19,  20]])

# Conditional Indexing 

In [218]:
a = np.arange(1,10)

In [219]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [221]:
a[a<5]

array([1, 2, 3, 4])

In [222]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [223]:
filt = a < 3

In [224]:
a[filt]

array([1, 2])

In [225]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
filt

array([ True,  True, False, False, False, False, False, False, False])

In [233]:
b = np.array([2,3,4,32,5,6,61,7,11])

In [234]:
b

array([ 2,  3,  4, 32,  5,  6, 61,  7, 11])

In [235]:
a == b

array([False, False, False, False,  True,  True, False, False, False])

In [236]:
a[a==b]

array([5, 6])

In [237]:
b[a==b]

array([5, 6])

In [238]:
a == [1]

array([ True, False, False, False, False, False, False, False, False])

In [239]:
a == 1

array([ True, False, False, False, False, False, False, False, False])

In [240]:
(a < 3) or (a > 5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [241]:
(a < 3) | (a > 5)

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [244]:
a[(a < 3) | (a > 5)]

array([1, 2, 6, 7, 8, 9])

In [245]:
filt = (a < 3) | (a > 5)

In [246]:
filt

array([ True,  True, False, False, False,  True,  True,  True,  True])

In [247]:
a[filt]

array([1, 2, 6, 7, 8, 9])

In [249]:
a[(a > 3) & (a <= 5)]

array([4, 5])

In [252]:
a[~((a > 3) & (a <= 5))] # 

array([1, 2, 3, 6, 7, 8, 9])

# Multidimensional Array Conditional Indexing

In [253]:
a = np.arange(1,21).reshape(4,5)

In [254]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [255]:
type(a)

numpy.ndarray

In [256]:
type(a<7)

numpy.ndarray

In [257]:
a>7

array([[False, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [258]:
a<7

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [259]:
a[a<7]

array([1, 2, 3, 4, 5, 6])

In [260]:
a[a<7].shape

(6,)

In [261]:
a = np.array([1,2,3,None])

In [262]:
a

array([1, 2, 3, None], dtype=object)

In [263]:
a==None

array([False, False, False,  True])

In [264]:
a[a==None]

array([None], dtype=object)

In [267]:
a = np.arange(-5,3).reshape(2,4)

In [270]:
a[(a<0)|(a==2)]

array([-5, -4, -3, -2, -1,  2])

# Sum

In [273]:
a = np.arange(1,21).reshape(4,5)

In [274]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [275]:
np.sum(a)

210

In [276]:
filt = a<5

In [277]:
np.sum(filt) # it's true count

4

In [279]:
filt 

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [280]:
np.sum(a[filt])

10

In [281]:
a[filt]

array([1, 2, 3, 4])

In [282]:
filt = (a>5) & (a<9)

In [283]:
np.sum(filt)

3

In [284]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [285]:
np.sum(a[filt])

21

In [286]:
np.sum(a[~filt])

189

In [287]:
np.sum(a[~(~filt)])

21

In [288]:
np.sum(a,axis=0)

array([34, 38, 42, 46, 50])

In [291]:
np.sum(a,axis=1)

array([15, 40, 65, 90])

In [292]:
a = np.arange(1,21).reshape(4,5).sum(axis=0)

In [293]:
a

array([34, 38, 42, 46, 50])

In [294]:
a.shape

(5,)

# All

In [295]:
a = np.arange(20).reshape(4,5)

In [296]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [297]:
a>-1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [298]:
np.all(a>-1)

True

In [302]:
np.all(a>5)

False

In [299]:
filt = a>-1

In [300]:
np.all(filt)

True

In [304]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [305]:
np.all(a>5,axis=1) # think layer by layer and evaluate them on x with an all method. Layer 1, layer 2 respectively

array([False, False,  True,  True])

In [306]:
np.all(a>5,axis=0)

array([False, False, False, False, False])

# Any

In [307]:
a = np.arange(20).reshape(4,5)

In [308]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [309]:
a>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True]])

In [310]:
np.any(a>17)

True

In [311]:
np.any(a>17,axis=0)

array([False, False, False,  True,  True])

In [312]:
np.any(a>17,axis=1)

array([False, False, False,  True])